---
- name: install,uninstall,upgrade multiple s/w's
  hosts: all
  tasks: 
     - name: install,uninstall,upgrade
       apt: 
         name: "{{item.a}}"
         state: "{{item.b}}"
         update_cache: "{{item.c}}"
       with_items:
            - {a: tree,b: present,c: no}
            - {a: maven,b: absent,c: no}
            - {a: git,b: latest,c: yes}
...
        

